name: Validar HTML y CSS

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Validar HTML
        run: npx --yes html-validate "**/*.html"